---
title: "Model Hack"
author: "203 Teaching Team"
date: "2023-02-28"
output: github_document
---

```{r load packages}
library(tidyverse)
```

This is in the printed page. 


```{r load data}
getwd() # pwd 
data         <- read.csv('~/MIDS/w203/live-session/data/housing_data.csv')
descriptions <- read.csv('~/MIDS/w203/live-session/data/housing_description.csv')
test_data    <- read.csv('~/MIDS/w203/live-session/data/boston_data.csv')
```

```{r print description of data}
descriptions
```


```{r create model evaluator}
evaluate_model <- function(model) { 
  ## takes in a model whose target is the 'price' variables
  ## returns mse
  
  mse <- function(predictions, truth) { 
    mean((predictions - truth)^2)
  }
  
  predictions_ <- model$fitted.values
  truth_       <- model$model$price
  
  mse_ <- mse(predictions=predictions_, truth=truth_)
  
  return(mse_)
  }
```

```{r lookat data}
data %>% 
  select(price, assess, bdrms, lotsize, sqrft) %>%
  pairs(pch = '.')
```


```{r fit models}
model_one <- lm(price ~ assess + assess, data = data)
model_two <- lm(price ~ assess + I(assess^2), data = data)
```

```{r evaluate models}
evaluate_model(model_one)
evaluate_model(model_two)
```


